<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AllLanguagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('all_languages')->delete();
        
        \DB::table('all_languages')->insert(array (
            0 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 1,
                'is_active' => 1,
                'iso_code' => 'en',
                'name' => 'English',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 2,
                'is_active' => 1,
                'iso_code' => 'aa',
                'name' => 'Afar',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 3,
                'is_active' => 1,
                'iso_code' => 'ab',
                'name' => 'Abkhazian',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 4,
                'is_active' => 1,
                'iso_code' => 'af',
                'name' => 'Afrikaans',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 5,
                'is_active' => 1,
                'iso_code' => 'am',
                'name' => 'Amharic',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 6,
                'is_active' => 1,
                'iso_code' => 'ar',
                'name' => 'Arabic',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 7,
                'is_active' => 1,
                'iso_code' => 'as',
                'name' => 'Assamese',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 8,
                'is_active' => 1,
                'iso_code' => 'ay',
                'name' => 'Aymara',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 9,
                'is_active' => 1,
                'iso_code' => 'az',
                'name' => 'Azerbaijani',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 10,
                'is_active' => 1,
                'iso_code' => 'ba',
                'name' => 'Bashkir',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 11,
                'is_active' => 1,
                'iso_code' => 'be',
                'name' => 'Belarusian',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 12,
                'is_active' => 1,
                'iso_code' => 'bg',
                'name' => 'Bulgarian',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 13,
                'is_active' => 1,
                'iso_code' => 'bh',
                'name' => 'Bihari',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 14,
                'is_active' => 1,
                'iso_code' => 'bi',
                'name' => 'Bislama',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 15,
                'is_active' => 1,
                'iso_code' => 'bn',
                'name' => 'Bengali/Bangla',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 16,
                'is_active' => 1,
                'iso_code' => 'bo',
                'name' => 'Tibetan',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 17,
                'is_active' => 1,
                'iso_code' => 'br',
                'name' => 'Breton',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 18,
                'is_active' => 1,
                'iso_code' => 'ca',
                'name' => 'Catalan',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 19,
                'is_active' => 1,
                'iso_code' => 'co',
                'name' => 'Corsican',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 20,
                'is_active' => 1,
                'iso_code' => 'cs',
                'name' => 'Czech',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 21,
                'is_active' => 1,
                'iso_code' => 'cy',
                'name' => 'Welsh',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 22,
                'is_active' => 1,
                'iso_code' => 'da',
                'name' => 'Danish',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 23,
                'is_active' => 1,
                'iso_code' => 'de',
                'name' => 'German',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 24,
                'is_active' => 1,
                'iso_code' => 'dz',
                'name' => 'Bhutani',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 25,
                'is_active' => 1,
                'iso_code' => 'el',
                'name' => 'Greek',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 26,
                'is_active' => 1,
                'iso_code' => 'eo',
                'name' => 'Esperanto',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 27,
                'is_active' => 1,
                'iso_code' => 'es',
                'name' => 'Spanish',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 28,
                'is_active' => 1,
                'iso_code' => 'et',
                'name' => 'Estonian',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 29,
                'is_active' => 1,
                'iso_code' => 'eu',
                'name' => 'Basque',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 30,
                'is_active' => 1,
                'iso_code' => 'fa',
                'name' => 'Persian',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 31,
                'is_active' => 1,
                'iso_code' => 'fi',
                'name' => 'Finnish',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 32,
                'is_active' => 1,
                'iso_code' => 'fj',
                'name' => 'Fiji',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 33,
                'is_active' => 1,
                'iso_code' => 'fo',
                'name' => 'Faeroese',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 34,
                'is_active' => 1,
                'iso_code' => 'fr',
                'name' => 'French',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 35,
                'is_active' => 1,
                'iso_code' => 'fy',
                'name' => 'Frisian',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 36,
                'is_active' => 1,
                'iso_code' => 'ga',
                'name' => 'Irish',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 37,
                'is_active' => 1,
                'iso_code' => 'gd',
                'name' => 'Scots/Gaelic',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 38,
                'is_active' => 1,
                'iso_code' => 'gl',
                'name' => 'Galician',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 39,
                'is_active' => 1,
                'iso_code' => 'gn',
                'name' => 'Guarani',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 40,
                'is_active' => 1,
                'iso_code' => 'gu',
                'name' => 'Gujarati',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 41,
                'is_active' => 1,
                'iso_code' => 'ha',
                'name' => 'Hausa',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 42,
                'is_active' => 1,
                'iso_code' => 'hi',
                'name' => 'Hindi',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 43,
                'is_active' => 1,
                'iso_code' => 'hr',
                'name' => 'Croatian',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 44,
                'is_active' => 1,
                'iso_code' => 'hu',
                'name' => 'Hungarian',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 45,
                'is_active' => 1,
                'iso_code' => 'hy',
                'name' => 'Armenian',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 46,
                'is_active' => 1,
                'iso_code' => 'ia',
                'name' => 'Interlingua',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 47,
                'is_active' => 1,
                'iso_code' => 'ie',
                'name' => 'Interlingue',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 48,
                'is_active' => 1,
                'iso_code' => 'ik',
                'name' => 'Inupiak',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 49,
                'is_active' => 1,
                'iso_code' => 'in',
                'name' => 'Indonesian',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 50,
                'is_active' => 1,
                'iso_code' => 'is',
                'name' => 'Icelandic',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 51,
                'is_active' => 1,
                'iso_code' => 'it',
                'name' => 'Italian',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 52,
                'is_active' => 1,
                'iso_code' => 'iw',
                'name' => 'Hebrew',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 53,
                'is_active' => 1,
                'iso_code' => 'ja',
                'name' => 'Japanese',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 54,
                'is_active' => 1,
                'iso_code' => 'ji',
                'name' => 'Yiddish',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 55,
                'is_active' => 1,
                'iso_code' => 'jw',
                'name' => 'Javanese',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 56,
                'is_active' => 1,
                'iso_code' => 'ka',
                'name' => 'Georgian',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 57,
                'is_active' => 1,
                'iso_code' => 'kk',
                'name' => 'Kazakh',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 58,
                'is_active' => 1,
                'iso_code' => 'kl',
                'name' => 'Greenlandic',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 59,
                'is_active' => 1,
                'iso_code' => 'km',
                'name' => 'Cambodian',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 60,
                'is_active' => 1,
                'iso_code' => 'kn',
                'name' => 'Kannada',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 61,
                'is_active' => 1,
                'iso_code' => 'ko',
                'name' => 'Korean',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 62,
                'is_active' => 1,
                'iso_code' => 'ks',
                'name' => 'Kashmiri',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 63,
                'is_active' => 1,
                'iso_code' => 'ku',
                'name' => 'Kurdish',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 64,
                'is_active' => 1,
                'iso_code' => 'ky',
                'name' => 'Kirghiz',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 65,
                'is_active' => 1,
                'iso_code' => 'la',
                'name' => 'Latin',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 66,
                'is_active' => 1,
                'iso_code' => 'ln',
                'name' => 'Lingala',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 67,
                'is_active' => 1,
                'iso_code' => 'lo',
                'name' => 'Laothian',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 68,
                'is_active' => 1,
                'iso_code' => 'lt',
                'name' => 'Lithuanian',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 69,
                'is_active' => 1,
                'iso_code' => 'lv',
                'name' => 'Latvian/Lettish',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 70,
                'is_active' => 1,
                'iso_code' => 'mg',
                'name' => 'Malagasy',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 71,
                'is_active' => 1,
                'iso_code' => 'mi',
                'name' => 'Maori',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 72,
                'is_active' => 1,
                'iso_code' => 'mk',
                'name' => 'Macedonian',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 73,
                'is_active' => 1,
                'iso_code' => 'ml',
                'name' => 'Malayalam',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 74,
                'is_active' => 1,
                'iso_code' => 'mn',
                'name' => 'Mongolian',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 75,
                'is_active' => 1,
                'iso_code' => 'mo',
                'name' => 'Moldavian',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 76,
                'is_active' => 1,
                'iso_code' => 'mr',
                'name' => 'Marathi',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 77,
                'is_active' => 1,
                'iso_code' => 'ms',
                'name' => 'Malay',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 78,
                'is_active' => 1,
                'iso_code' => 'mt',
                'name' => 'Maltese',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 79,
                'is_active' => 1,
                'iso_code' => 'my',
                'name' => 'Burmese',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 80,
                'is_active' => 1,
                'iso_code' => 'na',
                'name' => 'Nauru',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 81,
                'is_active' => 1,
                'iso_code' => 'ne',
                'name' => 'Nepali',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 82,
                'is_active' => 1,
                'iso_code' => 'nl',
                'name' => 'Dutch',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 83,
                'is_active' => 1,
                'iso_code' => 'no',
                'name' => 'Norwegian',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 84,
                'is_active' => 1,
                'iso_code' => 'oc',
                'name' => 'Occitan',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 85,
                'is_active' => 1,
                'iso_code' => 'om',
            'name' => '(Afan)/Oromoor/Oriya',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 86,
                'is_active' => 1,
                'iso_code' => 'pa',
                'name' => 'Punjabi',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 87,
                'is_active' => 1,
                'iso_code' => 'pl',
                'name' => 'Polish',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 88,
                'is_active' => 1,
                'iso_code' => 'ps',
                'name' => 'Pashto/Pushto',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 89,
                'is_active' => 1,
                'iso_code' => 'pt',
                'name' => 'Portuguese',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 90,
                'is_active' => 1,
                'iso_code' => 'qu',
                'name' => 'Quechua',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 91,
                'is_active' => 1,
                'iso_code' => 'rm',
                'name' => 'Rhaeto-Romance',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 92,
                'is_active' => 1,
                'iso_code' => 'rn',
                'name' => 'Kirundi',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 93,
                'is_active' => 1,
                'iso_code' => 'ro',
                'name' => 'Romanian',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 94,
                'is_active' => 1,
                'iso_code' => 'ru',
                'name' => 'Russian',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 95,
                'is_active' => 1,
                'iso_code' => 'rw',
                'name' => 'Kinyarwanda',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 96,
                'is_active' => 1,
                'iso_code' => 'sa',
                'name' => 'Sanskrit',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 97,
                'is_active' => 1,
                'iso_code' => 'sd',
                'name' => 'Sindhi',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 98,
                'is_active' => 1,
                'iso_code' => 'sg',
                'name' => 'Sangro',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 99,
                'is_active' => 1,
                'iso_code' => 'sh',
                'name' => 'Serbo-Croatian',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 100,
                'is_active' => 1,
                'iso_code' => 'si',
                'name' => 'Singhalese',
                'updated_at' => NULL,
            ),
        ));
        \DB::table('all_languages')->insert(array (
            0 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 101,
                'is_active' => 1,
                'iso_code' => 'sk',
                'name' => 'Slovak',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 102,
                'is_active' => 1,
                'iso_code' => 'sl',
                'name' => 'Slovenian',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 103,
                'is_active' => 1,
                'iso_code' => 'sm',
                'name' => 'Samoan',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 104,
                'is_active' => 1,
                'iso_code' => 'sn',
                'name' => 'Shona',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 105,
                'is_active' => 1,
                'iso_code' => 'so',
                'name' => 'Somali',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 106,
                'is_active' => 1,
                'iso_code' => 'sq',
                'name' => 'Albanian',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 107,
                'is_active' => 1,
                'iso_code' => 'sr',
                'name' => 'Serbian',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 108,
                'is_active' => 1,
                'iso_code' => 'ss',
                'name' => 'Siswati',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 109,
                'is_active' => 1,
                'iso_code' => 'st',
                'name' => 'Sesotho',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 110,
                'is_active' => 1,
                'iso_code' => 'su',
                'name' => 'Sundanese',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 111,
                'is_active' => 1,
                'iso_code' => 'sv',
                'name' => 'Swedish',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 112,
                'is_active' => 1,
                'iso_code' => 'sw',
                'name' => 'Swahili',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 113,
                'is_active' => 1,
                'iso_code' => 'ta',
                'name' => 'Tamil',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 114,
                'is_active' => 1,
                'iso_code' => 'te',
                'name' => 'Telugu',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 115,
                'is_active' => 1,
                'iso_code' => 'tg',
                'name' => 'Tajik',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 116,
                'is_active' => 1,
                'iso_code' => 'th',
                'name' => 'Thai',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 117,
                'is_active' => 1,
                'iso_code' => 'ti',
                'name' => 'Tigrinya',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 118,
                'is_active' => 1,
                'iso_code' => 'tk',
                'name' => 'Turkmen',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 119,
                'is_active' => 1,
                'iso_code' => 'tl',
                'name' => 'Tagalog',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 120,
                'is_active' => 1,
                'iso_code' => 'tn',
                'name' => 'Setswana',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 121,
                'is_active' => 1,
                'iso_code' => 'to',
                'name' => 'Tonga',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 122,
                'is_active' => 1,
                'iso_code' => 'tr',
                'name' => 'Turkish',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 123,
                'is_active' => 1,
                'iso_code' => 'ts',
                'name' => 'Tsonga',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 124,
                'is_active' => 1,
                'iso_code' => 'tt',
                'name' => 'Tatar',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 125,
                'is_active' => 1,
                'iso_code' => 'tw',
                'name' => 'Twi',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 126,
                'is_active' => 1,
                'iso_code' => 'uk',
                'name' => 'Ukrainian',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 127,
                'is_active' => 1,
                'iso_code' => 'ur',
                'name' => 'Urdu',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 128,
                'is_active' => 1,
                'iso_code' => 'uz',
                'name' => 'Uzbek',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 129,
                'is_active' => 1,
                'iso_code' => 'vi',
                'name' => 'Vietnamese',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 130,
                'is_active' => 1,
                'iso_code' => 'vo',
                'name' => 'Volapuk',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 131,
                'is_active' => 1,
                'iso_code' => 'wo',
                'name' => 'Wolof',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 132,
                'is_active' => 1,
                'iso_code' => 'xh',
                'name' => 'Xhosa',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 133,
                'is_active' => 1,
                'iso_code' => 'yo',
                'name' => 'Yoruba',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 134,
                'is_active' => 1,
                'iso_code' => 'zh',
                'name' => 'Chinese',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'created_at' => '2023-04-25 18:32:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'id' => 135,
                'is_active' => 1,
                'iso_code' => 'zu',
                'name' => 'Zulu',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}