<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'address_line_1' => 'D Ground People Colony',
                'address_line_2' => 'Faisalabad',
                'city_id' => 85437,
                'country_id' => 167,
                'cover_image' => NULL,
                'created_at' => '2023-08-01 16:54:49',
                'deleted_at' => NULL,
                'description' => 'Jack Testing Customer',
                'first_name' => 'Mary',
                'icon' => NULL,
                'id' => 1,
                'image' => '/images/profile_images/652fcc3d5fab9.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Jennifer',
                'state_id' => 3176,
                'updated_at' => '2023-11-03 15:41:58',
                'user_id' => 2,
                'user_name' => 'jack',
                'zip_code' => '38000',
            ),
            1 => 
            array (
                'address_line_1' => '123 Main Street
Anytown, USA
12345',
                'address_line_2' => '123 Main Street
Anytown, USA
12345',
                'city_id' => 8541,
                'country_id' => 19,
                'cover_image' => NULL,
                'created_at' => '2023-08-03 15:51:33',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'John',
                'icon' => NULL,
                'id' => 2,
                'image' => '/images/profile_images/652fc895e6093.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'James',
                'state_id' => 766,
                'updated_at' => '2024-01-22 16:19:14',
                'user_id' => 4,
                'user_name' => 'sir_john',
                'zip_code' => '38000',
            ),
            2 => 
            array (
                'address_line_1' => '123 Main Street
Anytown, USA
12345',
                'address_line_2' => '123 Main Street
Anytown, USA
12345',
                'city_id' => 8541,
                'country_id' => 19,
                'cover_image' => NULL,
                'created_at' => '2023-08-09 09:16:12',
                'deleted_at' => NULL,
                'description' => 'asd asds',
                'first_name' => 'Daniel',
                'icon' => NULL,
                'id' => 3,
                'image' => '/images/profile_images/652fcb5adc5a7.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Thomas',
                'state_id' => 766,
                'updated_at' => '2023-11-01 17:30:11',
                'user_id' => 18,
                'user_name' => 'sir_thomas',
                'zip_code' => '38000',
            ),
            3 => 
            array (
                'address_line_1' => '80880',
                'address_line_2' => 'Adress in Uk Street 1',
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-08-09 11:58:55',
                'deleted_at' => NULL,
                'description' => 'Hi there! I\'m Tonny, and I\'m passionate about [mention a few of your interests]. I\'m always up for trying new foods, discovering great music, and exploring new places. When I\'m not indulging in my hobbies, you can find me at work or spending quality time with family and friends. Feel free to connect with me; I love meeting new people and making meaningful connections.',
                'first_name' => 'Tonny',
                'icon' => NULL,
                'id' => 4,
                'image' => '/images/profile_images/6530f2797834d.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'Jaw',
                'state_id' => NULL,
                'updated_at' => '2024-05-02 16:45:34',
                'user_id' => 19,
                'user_name' => 'abc12',
                'zip_code' => 'Adress in Uk',
            ),
            4 => 
            array (
                'address_line_1' => 'house 325',
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-08-22 18:00:55',
                'deleted_at' => NULL,
                'description' => 'Isabella Carrington is a dynamic and results-driven attorney with a passion for justice and a strong commitment to her clients\' well-being. With a wealth of legal experience and a reputation for strategic thinking, Isabella has established herself as a trusted advocate known for her tenacity and dedication.

Education:

J.D. (Juris Doctor), Belleview Law School
B.A. in Political Science, University of Belleview',
                'first_name' => 'Isabella',
                'icon' => NULL,
                'id' => 5,
                'image' => '/images/lawyers/64ccd745aaa0b.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'Carrington',
                'state_id' => NULL,
                'updated_at' => '2024-05-11 12:00:49',
                'user_id' => 17,
                'user_name' => 'Isabella',
                'zip_code' => '38000',
            ),
            5 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-08-25 13:58:58',
                'deleted_at' => NULL,
                'description' => 'Sophia Lancaster is a skilled and compassionate attorney who is dedicated to advocating for her clients\' rights and ensuring access to justice. With a diverse legal background and a deep commitment to serving her community, Sophia has earned a reputation as a reliable and empathetic advocate.

Education:

J.D. (Juris Doctor), Summitville Law School
B.A. in Sociology, University of Summitville
Areas of Expertise:

Sophia specializes in family law, offering comprehensive legal support in matters such as divorce, child custody, spousal support, and adoption. Her extensive experience in mediation and negotiation enables her to guide her clients through challenging family situations while minimizing conflict. Sophia also provides legal assistance in estate planning, offering clients peace of mind for the future.',
                'first_name' => 'Sophia',
                'icon' => NULL,
                'id' => 6,
                'image' => '/images/lawyers/64ccd745aaa0b.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Lancaster',
                'state_id' => NULL,
                'updated_at' => '2023-08-25 13:58:58',
                'user_id' => 16,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            6 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-09-27 10:57:37',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Dean',
                'icon' => NULL,
                'id' => 7,
                'image' => '/images/lawyers/64ccd745aaa0b.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Jhon',
                'state_id' => NULL,
                'updated_at' => '2023-09-27 10:57:37',
                'user_id' => 20,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            7 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-09-27 15:52:55',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'john',
                'icon' => NULL,
                'id' => 8,
                'image' => '/images/lawyers/64ccd745aaa0b.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'wick',
                'state_id' => NULL,
                'updated_at' => '2023-12-05 15:27:39',
                'user_id' => 22,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            8 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-10-26 19:54:30',
                'deleted_at' => '2023-10-26 20:02:45',
                'description' => NULL,
                'first_name' => 'Faizan',
                'icon' => NULL,
                'id' => 9,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Fazal',
                'state_id' => NULL,
                'updated_at' => '2023-10-26 20:02:45',
                'user_id' => 40,
                'user_name' => 'sir_faizan',
                'zip_code' => NULL,
            ),
            9 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-10-26 20:12:05',
                'deleted_at' => '2023-10-26 20:12:59',
                'description' => NULL,
                'first_name' => 'Faizan',
                'icon' => NULL,
                'id' => 10,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Fazal',
                'state_id' => NULL,
                'updated_at' => '2023-10-26 20:12:59',
                'user_id' => 42,
                'user_name' => 'sir_fazal',
                'zip_code' => NULL,
            ),
            10 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-01 17:37:10',
                'deleted_at' => '2023-11-01 17:38:48',
                'description' => 'hello i am a customer hello',
                'first_name' => 'john',
                'icon' => NULL,
                'id' => 11,
                'image' => '/images/customers/6542467632fc0.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'dave',
                'state_id' => NULL,
                'updated_at' => '2023-11-01 17:38:48',
                'user_id' => 3,
                'user_name' => 'sir_dave',
                'zip_code' => NULL,
            ),
            11 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 02:19:00',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Mahmoud',
                'icon' => NULL,
                'id' => 12,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ali',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 02:19:00',
                'user_id' => 45,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            12 => 
            array (
                'address_line_1' => 'El Coca',
                'address_line_2' => NULL,
                'city_id' => 31506,
                'country_id' => 64,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 04:51:14',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'José Luis',
                'icon' => NULL,
                'id' => 13,
                'image' => '/images/profile_images/65bba75d3f0e2.png',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Orbes',
                'state_id' => 2926,
                'updated_at' => '2024-02-01 19:47:16',
                'user_id' => 46,
                'user_name' => 'orbesjoe',
                'zip_code' => '220102',
            ),
            13 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 10:12:31',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'dd',
                'icon' => NULL,
                'id' => 14,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'dd',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 10:12:31',
                'user_id' => 48,
                'user_name' => 'dd',
                'zip_code' => NULL,
            ),
            14 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 13:48:49',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'mahmoud',
                'icon' => NULL,
                'id' => 15,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'subhy',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 16:15:39',
                'user_id' => 49,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            15 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 16:13:45',
                'deleted_at' => NULL,
                'description' => '',
                'first_name' => 'sina',
                'icon' => NULL,
                'id' => 16,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'najafi',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 16:13:45',
                'user_id' => 53,
                'user_name' => NULL,
                'zip_code' => 'nw',
            ),
            16 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 16:15:35',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'sinasi',
                'icon' => NULL,
                'id' => 17,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'sinasi',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 16:15:35',
                'user_id' => 54,
                'user_name' => 'sinsinati',
                'zip_code' => NULL,
            ),
            17 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:20:32',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'test',
                'icon' => NULL,
                'id' => 18,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'test',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 18:20:32',
                'user_id' => 55,
                'user_name' => 'testetes',
                'zip_code' => NULL,
            ),
            18 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:27:46',
                'deleted_at' => NULL,
                'description' => '',
                'first_name' => 'Jack',
                'icon' => NULL,
                'id' => 19,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Ma',
                'state_id' => NULL,
                'updated_at' => '2023-11-23 18:28:35',
                'user_id' => 56,
                'user_name' => NULL,
                'zip_code' => '38000',
            ),
            19 => 
            array (
                'address_line_1' => '12344',
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:30:50',
                'deleted_at' => NULL,
                'description' => 'sweet',
                'first_name' => 'ddw',
                'icon' => NULL,
                'id' => 20,
                'image' => '/files/profile_images/1705387746scaled_image_picker3190099173755574307.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'User',
                'state_id' => NULL,
                'updated_at' => '2024-05-19 14:04:22',
                'user_id' => 57,
                'user_name' => 'seeker',
                'zip_code' => 'london',
            ),
            20 => 
            array (
                'address_line_1' => '380009',
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-24 19:57:39',
                'deleted_at' => NULL,
                'description' => 'test2',
                'first_name' => 'Consultant test',
                'icon' => NULL,
                'id' => 21,
                'image' => '/files/profile_images/1707462609scaled_2f0a97e1-091b-4b29-9301-57403f8a8ebe9097756696303463482.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'Lawyer',
                'state_id' => NULL,
                'updated_at' => '2024-05-15 02:57:12',
                'user_id' => 58,
                'user_name' => 'test1',
                'zip_code' => 'test3',
            ),
            21 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-02 14:07:38',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'leo',
                'icon' => NULL,
                'id' => 22,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Nardo',
                'state_id' => NULL,
                'updated_at' => '2023-12-02 14:07:38',
                'user_id' => 61,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            22 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-03 23:15:32',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Daniel',
                'icon' => NULL,
                'id' => 23,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Starred',
                'state_id' => NULL,
                'updated_at' => '2023-12-03 23:15:32',
                'user_id' => 63,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            23 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-06 17:11:50',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Faizan',
                'icon' => NULL,
                'id' => 24,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Fazal',
                'state_id' => NULL,
                'updated_at' => '2023-12-06 17:11:50',
                'user_id' => 64,
                'user_name' => 'sir_faizan1',
                'zip_code' => NULL,
            ),
            24 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-07 18:04:05',
                'deleted_at' => NULL,
                'description' => '',
                'first_name' => 'KARAKKEEL',
                'icon' => NULL,
                'id' => 25,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'SARITH',
                'state_id' => NULL,
                'updated_at' => '2023-12-07 18:18:57',
                'user_id' => 65,
                'user_name' => NULL,
                'zip_code' => '2345654',
            ),
            25 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-09 13:11:15',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'nik',
                'icon' => NULL,
                'id' => 26,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'roy',
                'state_id' => NULL,
                'updated_at' => '2023-12-09 13:11:15',
                'user_id' => 66,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            26 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-11 17:22:48',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'odind',
                'icon' => NULL,
                'id' => 27,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'odjdj',
                'state_id' => NULL,
                'updated_at' => '2023-12-11 17:22:48',
                'user_id' => 67,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            27 => 
            array (
                'address_line_1' => '100',
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-14 00:11:38',
                'deleted_at' => NULL,
                'description' => 'fh',
                'first_name' => 'dagi',
                'icon' => NULL,
                'id' => 28,
                'image' => '/files/profile_images/1703170511scaled_1000193631.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'abea',
                'state_id' => NULL,
                'updated_at' => '2023-12-21 19:55:11',
                'user_id' => 68,
                'user_name' => 'fg',
                'zip_code' => 'ch',
            ),
            28 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-18 16:36:11',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'n',
                'icon' => NULL,
                'id' => 29,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'n',
                'state_id' => NULL,
                'updated_at' => '2023-12-18 16:36:11',
                'user_id' => 70,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            29 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-22 17:35:16',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'dagi abea',
                'icon' => NULL,
                'id' => 30,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'dagi abea',
                'state_id' => NULL,
                'updated_at' => '2023-12-22 17:35:16',
                'user_id' => 73,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            30 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-23 06:24:13',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Trung',
                'icon' => NULL,
                'id' => 31,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Dao',
                'state_id' => NULL,
                'updated_at' => '2023-12-23 06:24:13',
                'user_id' => 76,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            31 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-24 12:59:22',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'nguyen',
                'icon' => NULL,
                'id' => 32,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'nhat',
                'state_id' => NULL,
                'updated_at' => '2023-12-24 12:59:22',
                'user_id' => 77,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            32 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-25 13:46:08',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'nhat',
                'icon' => NULL,
                'id' => 33,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'nem',
                'state_id' => NULL,
                'updated_at' => '2023-12-25 13:46:08',
                'user_id' => 79,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            33 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-03 13:44:06',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Bui',
                'icon' => NULL,
                'id' => 34,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Chan',
                'state_id' => NULL,
                'updated_at' => '2024-01-03 13:44:06',
                'user_id' => 83,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            34 => 
            array (
                'address_line_1' => 'hhhh',
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-04 12:54:23',
                'deleted_at' => NULL,
                'description' => 'hhjj',
                'first_name' => 'nhat',
                'icon' => NULL,
                'id' => 35,
                'image' => '/files/profile_images/1704683155scaled_928e145a-4407-4699-8788-c09bf78b8cdc5485286519308985743.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'nhat',
                'state_id' => NULL,
                'updated_at' => '2024-01-08 08:05:55',
                'user_id' => 84,
                'user_name' => 'hssj',
                'zip_code' => 'hhhh',
            ),
            35 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-06 15:46:34',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'hisham',
                'icon' => NULL,
                'id' => 36,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'alaimo',
                'state_id' => NULL,
                'updated_at' => '2024-01-06 15:46:34',
                'user_id' => 86,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            36 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-08 12:13:41',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'test',
                'icon' => NULL,
                'id' => 37,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'luat',
                'state_id' => NULL,
                'updated_at' => '2024-01-08 12:13:41',
                'user_id' => 87,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            37 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-09 04:19:11',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'anamul',
                'icon' => NULL,
                'id' => 38,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'haque',
                'state_id' => NULL,
                'updated_at' => '2024-01-09 04:19:11',
                'user_id' => 89,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            38 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-23 17:13:03',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'mahmoud',
                'icon' => NULL,
                'id' => 39,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ahmed',
                'state_id' => NULL,
                'updated_at' => '2024-01-23 17:13:03',
                'user_id' => 97,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            39 => 
            array (
                'address_line_1' => '123 Main Street City, State 12345 Country',
                'address_line_2' => '123 Main Street City, State 12345 Country',
                'city_id' => 1,
                'country_id' => 1,
                'cover_image' => NULL,
                'created_at' => '2024-01-24 19:07:05',
                'deleted_at' => NULL,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'first_name' => 'Laura',
                'icon' => NULL,
                'id' => 40,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Parker',
                'state_id' => 1,
                'updated_at' => '2024-05-07 17:41:46',
                'user_id' => 36,
                'user_name' => NULL,
                'zip_code' => '1234567',
            ),
            40 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-29 17:42:28',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'diwakar',
                'icon' => NULL,
                'id' => 41,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'pathak',
                'state_id' => NULL,
                'updated_at' => '2024-01-29 17:42:28',
                'user_id' => 99,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            41 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-29 17:42:57',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'diwakar',
                'icon' => NULL,
                'id' => 42,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'kumat',
                'state_id' => NULL,
                'updated_at' => '2024-01-29 17:42:57',
                'user_id' => 100,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            42 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-30 13:32:12',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'eu',
                'icon' => NULL,
                'id' => 43,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'sou',
                'state_id' => NULL,
                'updated_at' => '2024-01-30 13:32:12',
                'user_id' => 102,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            43 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-01 16:34:46',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'lobe',
                'icon' => NULL,
                'id' => 44,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'lamu',
                'state_id' => NULL,
                'updated_at' => '2024-02-01 16:34:46',
                'user_id' => 103,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            44 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-06 09:57:39',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'stal',
                'icon' => NULL,
                'id' => 45,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Mor',
                'state_id' => NULL,
                'updated_at' => '2024-02-06 09:57:39',
                'user_id' => 105,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            45 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-11 03:34:43',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'prueba',
                'icon' => NULL,
                'id' => 46,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'prueba',
                'state_id' => NULL,
                'updated_at' => '2024-02-11 03:34:43',
                'user_id' => 107,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            46 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-15 09:13:44',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'R',
                'icon' => NULL,
                'id' => 47,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'K',
                'state_id' => NULL,
                'updated_at' => '2024-02-15 09:13:44',
                'user_id' => 110,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            47 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-18 16:46:27',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'ahmed',
                'icon' => NULL,
                'id' => 48,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'mohamed',
                'state_id' => NULL,
                'updated_at' => '2024-02-18 16:46:27',
                'user_id' => 113,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            48 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-22 02:47:07',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Gul',
                'icon' => NULL,
                'id' => 49,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Zar',
                'state_id' => NULL,
                'updated_at' => '2024-02-22 02:47:07',
                'user_id' => 115,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            49 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-02-24 05:11:54',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'مشاوي',
                'icon' => NULL,
                'id' => 50,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ال',
                'state_id' => NULL,
                'updated_at' => '2024-02-24 05:11:54',
                'user_id' => 117,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            50 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-03-07 15:05:49',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Muhammad',
                'icon' => NULL,
                'id' => 51,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'last_name' => 'Rehan',
                'state_id' => NULL,
                'updated_at' => '2024-03-07 17:57:07',
                'user_id' => 120,
                'user_name' => 'rehan',
                'zip_code' => NULL,
            ),
            51 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-03-20 14:06:19',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Zeshan',
                'icon' => NULL,
                'id' => 52,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Ahmed',
                'state_id' => NULL,
                'updated_at' => '2024-03-20 14:06:19',
                'user_id' => 124,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            52 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-03-30 19:32:28',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Nishanth',
                'icon' => NULL,
                'id' => 53,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'TP',
                'state_id' => NULL,
                'updated_at' => '2024-03-30 19:32:28',
                'user_id' => 128,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            53 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-03-30 20:57:44',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'adams',
                'icon' => NULL,
                'id' => 54,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'bgh',
                'state_id' => NULL,
                'updated_at' => '2024-03-30 20:57:44',
                'user_id' => 129,
                'user_name' => 'adams',
                'zip_code' => NULL,
            ),
            54 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-01 15:41:08',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'amir',
                'icon' => NULL,
                'id' => 55,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'as',
                'state_id' => NULL,
                'updated_at' => '2024-04-01 15:41:08',
                'user_id' => 130,
                'user_name' => 'mrami',
                'zip_code' => NULL,
            ),
            55 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-06 20:30:33',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'roko',
                'icon' => NULL,
                'id' => 56,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'kol',
                'state_id' => NULL,
                'updated_at' => '2024-04-06 20:30:33',
                'user_id' => 133,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            56 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-17 00:49:50',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'sfx',
                'icon' => NULL,
                'id' => 57,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'fgvg',
                'state_id' => NULL,
                'updated_at' => '2024-04-17 00:49:50',
                'user_id' => 136,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            57 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-20 21:08:01',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'tttv',
                'icon' => NULL,
                'id' => 58,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ggg',
                'state_id' => NULL,
                'updated_at' => '2024-04-20 21:08:01',
                'user_id' => 137,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            58 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-21 06:17:10',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Indrasen',
                'icon' => NULL,
                'id' => 59,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'Srivastava',
                'state_id' => NULL,
                'updated_at' => '2024-04-21 06:17:10',
                'user_id' => 138,
                'user_name' => 'Indrasen',
                'zip_code' => NULL,
            ),
            59 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-25 11:44:29',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'israr',
                'icon' => NULL,
                'id' => 60,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ahmed',
                'state_id' => NULL,
                'updated_at' => '2024-04-25 11:44:29',
                'user_id' => 140,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            60 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-04-30 19:35:30',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'valdir',
                'icon' => NULL,
                'id' => 61,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'correia',
                'state_id' => NULL,
                'updated_at' => '2024-04-30 19:35:30',
                'user_id' => 142,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            61 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-05-09 18:35:40',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Alok',
                'icon' => NULL,
                'id' => 62,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'shi',
                'state_id' => NULL,
                'updated_at' => '2024-05-09 18:35:40',
                'user_id' => 143,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            62 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-05-11 13:50:49',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'a',
                'icon' => NULL,
                'id' => 63,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'mamun',
                'state_id' => NULL,
                'updated_at' => '2024-05-11 13:50:49',
                'user_id' => 145,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
            63 => 
            array (
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'city_id' => NULL,
                'country_id' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-05-12 01:47:38',
                'deleted_at' => NULL,
                'description' => NULL,
                'first_name' => 'Aly',
                'icon' => NULL,
                'id' => 64,
                'image' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'last_name' => 'ttt',
                'state_id' => NULL,
                'updated_at' => '2024-05-12 01:47:38',
                'user_id' => 146,
                'user_name' => NULL,
                'zip_code' => NULL,
            ),
        ));
        
        
    }
}