<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GatewaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('gateways')->delete();

        \DB::table('gateways')->insert(array (
            0 =>
            array (
                'code' => 'paypal',
                'convention_rate' => '0.01200000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"USD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 1,
                'image' => '/files/payment_gateways/1705075352paypal.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Paypal',
                'note' => '',
                'parameters' => '{"cleint_id":"asdasd93485","secret":"upadasdml234"}',
                'percentage_charge' => '1.0000',
                'sort_by' => 14,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:02:32',
            ),
            1 =>
            array (
                'code' => 'stripe',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => '{"webhook":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 2,
                'image' => '/files/payment_gateways/1705075857stripe.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Stripe ',
                'note' => '',
                'parameters' => '{"secret_key":"sk_test_4mIgs731P1pD8aEEO57Ytf5v","publishable_key":"pk_test_0OgQlXP7CRZ0AzpdcYQfM496","endpoint_secret":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 23,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:10:57',
            ),
            2 =>
            array (
                'code' => 'skrill',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BHD":"BHD","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","INR":"INR","ISK":"ISK","JOD":"JOD","JPY":"JPY","KRW":"KRW","KWD":"KWD","MAD":"MAD","MYR":"MYR","NOK":"NOK","NZD":"NZD","OMR":"OMR","PLN":"PLN","QAR":"QAR","RON":"RON","RSD":"RSD","SAR":"SAR","SEK":"SEK","SGD":"SGD","THB":"THB","TND":"TND","TRY":"TRY","TWD":"TWD","USD":"USD","ZAR":"ZAR","COP":"COP"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 3,
                'image' => '/files/payment_gateways/1705075839skrill.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Skrill',
                'note' => '',
                'parameters' => '{"pay_to_email":"**************","secret_key":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 22,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:10:39',
            ),
            3 =>
            array (
                'code' => 'perfectmoney',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 4,
                'image' => '/files/payment_gateways/1705075787perfect-money.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Perfect Money',
                'note' => '',
                'parameters' => '{"passphrase":"**************","payee_account":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 18,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:09:47',
            ),
            4 =>
            array (
                'code' => 'paytm',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AUD":"AUD","ARS":"ARS","BDT":"BDT","BRL":"BRL","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","HRK":"HRK","CZK":"CZK","DKK":"DKK","EGP":"EGP","EUR":"EUR","GEL":"GEL","GHS":"GHS","HKD":"HKD","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JPY":"JPY","KES":"KES","MYR":"MYR","MXN":"MXN","MAD":"MAD","NPR":"NPR","NZD":"NZD","NGN":"NGN","NOK":"NOK","PKR":"PKR","PEN":"PEN","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SGD":"SGD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","THB":"THB","TRY":"TRY","UGX":"UGX","UAH":"UAH","AED":"AED","GBP":"GBP","USD":"USD","VND":"VND","XOF":"XOF"}}',
                'currency' => 'INR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 5,
                'image' => '/files/payment_gateways/1705075695payTM.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'PayTM',
                'note' => '',
                'parameters' => '{"MID":"**************","merchant_key":"**************","WEBSITE":"**************","INDUSTRY_TYPE_ID":"**************","CHANNEL_ID":"**************","environment_url":"**************","process_transaction_url":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 16,
                'status' => 1,
                'symbol' => 'INR',
                'updated_at' => '2024-01-12 21:08:16',
            ),
            5 =>
            array (
                'code' => 'payeer',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR","RUB":"RUB"}}',
                'currency' => 'RUB',
                'deleted_at' => NULL,
                'extra_parameters' => '{"status":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 6,
                'image' => '/files/payment_gateways/1705075215payeer.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Payeer',
                'note' => '',
                'parameters' => '{"merchant_id":"P1109116078","secret_key":"m5R81LJ7Ieu33h8Y"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 13,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:00:15',
            ),
            6 =>
            array (
                'code' => 'paystack',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"USD":"USD","NGN":"NGN"}}',
                'currency' => 'NGN',
                'deleted_at' => NULL,
                'extra_parameters' => '{"callback":"ipn","webhook":"ipn"}
',
                'fixed_charge' => '0.50000000',
                'id' => 7,
                'image' => '/files/payment_gateways/1705075369paystack.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'PayStack',
                'note' => '',
                'parameters' => '{"public_key":"***************","secret_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 15,
                'status' => 1,
                'symbol' => 'NGN',
                'updated_at' => '2024-01-12 21:02:49',
            ),
            7 =>
            array (
                'code' => 'voguepay',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"NGN":"NGN","USD":"USD","EUR":"EUR","GBP":"GBP","ZAR":"ZAR","JPY":"JPY","INR":"INR","AUD":"AUD","CAD":"CAD","NZD":"NZD","NOK":"NOK","PLN":"PLN"}}








',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 8,
                'image' => '/files/payment_gateways/1705075868VoguePay .png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'VoguePay',
                'note' => '',
                'parameters' => '{"merchant_id":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 21,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:11:08',
            ),
            8 =>
            array (
                'code' => 'flutterwave',
                'convention_rate' => '0.01200000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"KES":"KES","GHS":"GHS","NGN":"NGN","USD":"USD","GBP":"GBP","EUR":"EUR","UGX":"UGX","TZS":"TZS"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 9,
                'image' => '/files/payment_gateways/1705074939Flutterwave.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Flutterwave',
                'note' => '',
                'parameters' => '{"public_key":"***************","secret_key":"***************","encryption_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 8,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:55:39',
            ),
            9 =>
            array (
                'code' => 'razorpay',
                'convention_rate' => '10.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0": {"INR": "INR"}}',
                'currency' => 'INR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 10,
                'image' => '/files/payment_gateways/1705075802razorpay.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'RazorPay',
                'note' => '',
                'parameters' => '{"key_id":"rzp_test_LbK7OKIrPbCFo3","key_secret":"j7Gjtvc6zr4eFkUTqfpuAZVd"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 19,
                'status' => 1,
                'symbol' => 'INR',
                'updated_at' => '2024-01-12 21:10:02',
            ),
            10 =>
            array (
                'code' => 'instamojo',
                'convention_rate' => '73.51000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"INR":"INR"}}',
                'currency' => 'INR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 11,
                'image' => '/files/payment_gateways/1705074994instamojo.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'instamojo',
                'note' => '',
                'parameters' => '{"api_key":"***************","auth_token":"***************","salt":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 9,
                'status' => 1,
                'symbol' => 'INR',
                'updated_at' => '2024-01-12 20:56:34',
            ),
            11 =>
            array (
                'code' => 'mollie',
                'convention_rate' => '0.01200000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BRL":"BRL","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","ISK":"ISK","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD","USD":"USD","ZAR":"ZAR"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 12,
                'image' => '/files/payment_gateways/1705075135mollie.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Mollie',
                'note' => '',
                'parameters' => '{"api_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 11,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:58:55',
            ),
            12 =>
            array (
                'code' => 'twocheckout',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AFN":"AFN","ALL":"ALL","DZD":"DZD","ARS":"ARS","AUD":"AUD","AZN":"AZN","BSD":"BSD","BDT":"BDT","BBD":"BBD","BZD":"BZD","BMD":"BMD","BOB":"BOB","BWP":"BWP","BRL":"BRL","GBP":"GBP","BND":"BND","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","HRK":"HRK","CZK":"CZK","DKK":"DKK","DOP":"DOP","XCD":"XCD","EGP":"EGP","EUR":"EUR","FJD":"FJD","GTQ":"GTQ","HKD":"HKD","HNL":"HNL","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JMD":"JMD","JPY":"JPY","KZT":"KZT","KES":"KES","LAK":"LAK","MMK":"MMK","LBP":"LBP","LRD":"LRD","MOP":"MOP","MYR":"MYR","MVR":"MVR","MRO":"MRO","MUR":"MUR","MXN":"MXN","MAD":"MAD","NPR":"NPR","TWD":"TWD","NZD":"NZD","NIO":"NIO","NOK":"NOK","PKR":"PKR","PGK":"PGK","PEN":"PEN","PHP":"PHP","PLN":"PLN","QAR":"QAR","RON":"RON","RUB":"RUB","WST":"WST","SAR":"SAR","SCR":"SCR","SGD":"SGD","SBD":"SBD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","SYP":"SYP","THB":"THB","TOP":"TOP","TTD":"TTD","TRY":"TRY","UAH":"UAH","AED":"AED","USD":"USD","VUV":"VUV","VND":"VND","XOF":"XOF","YER":"YER"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => '{"approved_url":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 13,
                'image' => '/files/payment_gateways/17050733572checkout.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => '2checkout',
                'note' => '',
                'parameters' => '{"merchant_code":"********************","secret_key":"********************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 24,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:29:17',
            ),
            13 =>
            array (
                'code' => 'authorizenet',
                'convention_rate' => '0.01200000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AUD":"AUD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","USD":"USD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 14,
                'image' => '/files/payment_gateways/1705073391Authorize-net.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Authorize.Net',
                'note' => '',
                'parameters' => '{"login_id":"********************","current_transaction_key":"********************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:29:51',
            ),
            14 =>
            array (
                'code' => 'securionpay',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AFN":"AFN", "DZD":"DZD", "ARS":"ARS", "AUD":"AUD", "BHD":"BHD", "BDT":"BDT", "BYR":"BYR", "BAM":"BAM", "BWP":"BWP", "BRL":"BRL", "BND":"BND", "BGN":"BGN", "CAD":"CAD", "CLP":"CLP", "CNY":"CNY", "COP":"COP", "KMF":"KMF", "HRK":"HRK", "CZK":"CZK", "DKK":"DKK", "DJF":"DJF", "DOP":"DOP", "EGP":"EGP", "ETB":"ETB", "ERN":"ERN", "EUR":"EUR", "GEL":"GEL", "HKD":"HKD", "HUF":"HUF", "ISK":"ISK", "INR":"INR", "IDR":"IDR", "IRR":"IRR", "IQD":"IQD", "ILS":"ILS", "JMD":"JMD", "JPY":"JPY", "JOD":"JOD", "KZT":"KZT", "KES":"KES", "KWD":"KWD", "KGS":"KGS", "LVL":"LVL", "LBP":"LBP", "LTL":"LTL", "MOP":"MOP", "MKD":"MKD", "MGA":"MGA", "MWK":"MWK", "MYR":"MYR", "MUR":"MUR", "MXN":"MXN", "MDL":"MDL", "MAD":"MAD", "MZN":"MZN", "NAD":"NAD", "NPR":"NPR", "ANG":"ANG", "NZD":"NZD", "NOK":"NOK", "OMR":"OMR", "PKR":"PKR", "PEN":"PEN", "PHP":"PHP", "PLN":"PLN", "QAR":"QAR", "RON":"RON", "RUB":"RUB", "SAR":"SAR", "RSD":"RSD", "SGD":"SGD", "ZAR":"ZAR", "KRW":"KRW", "IKR":"IKR", "LKR":"LKR", "SEK":"SEK", "CHF":"CHF", "SYP":"SYP", "TWD":"TWD", "TZS":"TZS", "THB":"THB", "TND":"TND", "TRY":"TRY", "UAH":"UAH", "AED":"AED", "GBP":"GBP", "USD":"USD", "VEB":"VEB", "VEF":"VEF", "VND":"VND", "XOF":"XOF", "YER":"YER", "ZMK":"ZMK"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 15,
                'image' => '/files/payment_gateways/1705075825Securionpay.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'SecurionPay',
                'note' => '',
                'parameters' => '{"public_key":"**************","secret_key":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 20,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:10:25',
            ),
            15 =>
            array (
                'code' => 'payumoney',
                'convention_rate' => '0.87000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"INR":"INR"}}',
                'currency' => 'INR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 16,
                'image' => '/files/payment_gateways/1705075719payumoney.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'PayUmoney',
                'note' => '',
                'parameters' => '{"merchant_key":"**************","salt":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 17,
                'status' => 1,
                'symbol' => 'INR',
                'updated_at' => '2024-01-12 21:08:40',
            ),
            16 =>
            array (
                'code' => 'mercadopago',
                'convention_rate' => '0.06300000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"ARS":"ARS","BOB":"BOB","BRL":"BRL","CLF":"CLF","CLP":"CLP","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","DOP":"DOP","EUR":"EUR","GTQ":"GTQ","HNL":"HNL","MXN":"MXN","NIO":"NIO","PAB":"PAB","PEN":"PEN","PYG":"PYG","USD":"USD","UYU":"UYU","VEF":"VEF","VES":"VES"}}',
                'currency' => 'BRL',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 17,
                'image' => '/files/payment_gateways/1705075107mercado-pago.png',
                'max_amount' => '371500000.12000000',
                'min_amount' => '3715.12000000',
                'name' => 'Mercado Pago',
                'note' => '',
                'parameters' => '{"access_token":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 10,
                'status' => 1,
                'symbol' => 'BRL',
                'updated_at' => '2024-01-12 20:58:27',
            ),
            17 =>
            array (
                'code' => 'coingate',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 18,
                'image' => '/files/payment_gateways/1705074864Coingate.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Coingate',
                'note' => '',
                'parameters' => '{"api_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 7,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:54:24',
            ),
            18 =>
            array (
                'code' => 'coinbasecommerce',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"AED":"AED","AFN":"AFN","ALL":"ALL","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZN":"AZN","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYN":"BYN","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLF":"CLF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","CVE":"CVE","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHS":"GHS","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZN":"MZN","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PYG":"PYG","QAR":"QAR","RON":"RON","RSD":"RSD","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDG":"SDG","SEK":"SEK","SGD":"SGD","SHP":"SHP","SLL":"SLL","SOS":"SOS","SRD":"SRD","SSP":"SSP","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMT":"TMT","TND":"TND","TOP":"TOP","TRY":"TRY","TTD":"TTD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMW":"ZMW","ZWL":"ZWL"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => '{"webhook":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 19,
                'image' => '/files/payment_gateways/1705074880coinbase-commerce.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Coinbase Commerce',
                'note' => '',
                'parameters' => '{"api_key":"***************","secret":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 3,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 20:54:40',
            ),
            19 =>
            array (
                'code' => 'monnify',
                'convention_rate' => '4.52000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"NGN":"NGN"}}',
                'currency' => 'NGN',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 20,
                'image' => '/files/payment_gateways/1705075174monnify.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Monnify',
                'note' => '',
                'parameters' => '{"api_key":"***************","secret_key":"***************","contract_code":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 12,
                'status' => 1,
                'symbol' => 'NGN',
                'updated_at' => '2024-01-12 20:59:34',
            ),
            20 =>
            array (
                'code' => 'blockio',
                'convention_rate' => '0.00004200',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"1":{"BTC":"BTC","LTC":"LTC","DOGE":"DOGE"}}',
                'currency' => 'BTC',
                'deleted_at' => NULL,
                'extra_parameters' => '{"cron":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 21,
                'image' => '/files/payment_gateways/1705076280block-io.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '10.10000000',
                'name' => 'Block.io',
                'note' => '',
                'parameters' => '{"api_key":"1e83-f033-177a-1644","api_pin":"A62C503A6032C8C3"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 2,
                'status' => 1,
                'symbol' => 'BTC',
                'updated_at' => '2024-01-12 21:18:00',
            ),
            21 =>
            array (
                'code' => 'coinpayments',
                'convention_rate' => '0.00000000',
                'created_at' => '2020-09-10 14:05:02',
            'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","ISK":"ISK","JPY":"JPY","KRW":"KRW","NZD":"NZD","PLN":"PLN","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD"},"1":{"BTC":"Bitcoin","BTC.LN":"Bitcoin (Lightning Network)","LTC":"Litecoin","CPS":"CPS Coin","VLX":"Velas","APL":"Apollo","AYA":"Aryacoin","BAD":"Badcoin","BCD":"Bitcoin Diamond","BCH":"Bitcoin Cash","BCN":"Bytecoin","BEAM":"BEAM","BITB":"Bean Cash","BLK":"BlackCoin","BSV":"Bitcoin SV","BTAD":"Bitcoin Adult","BTG":"Bitcoin Gold","BTT":"BitTorrent","CLOAK":"CloakCoin","CLUB":"ClubCoin","CRW":"Crown","CRYP":"CrypticCoin","CRYT":"CryTrExCoin","CURE":"CureCoin","DASH":"DASH","DCR":"Decred","DEV":"DeviantCoin","DGB":"DigiByte","DOGE":"Dogecoin","EBST":"eBoost","EOS":"EOS","ETC":"Ether Classic","ETH":"Ethereum","ETN":"Electroneum","EUNO":"EUNO","EXP":"EXP","Expanse":"Expanse","FLASH":"FLASH","GAME":"GameCredits","GLC":"Goldcoin","GRS":"Groestlcoin","KMD":"Komodo","LOKI":"LOKI","LSK":"LSK","MAID":"MaidSafeCoin","MUE":"MonetaryUnit","NAV":"NAV Coin","NEO":"NEO","NMC":"Namecoin","NVST":"NVO Token","NXT":"NXT","OMNI":"OMNI","PINK":"PinkCoin","PIVX":"PIVX","POT":"PotCoin","PPC":"Peercoin","PROC":"ProCurrency","PURA":"PURA","QTUM":"QTUM","RES":"Resistance","RVN":"Ravencoin","RVR":"RevolutionVR","SBD":"Steem Dollars","SMART":"SmartCash","SOXAX":"SOXAX","STEEM":"STEEM","STRAT":"STRAT","SYS":"Syscoin","TPAY":"TokenPay","TRIGGERS":"Triggers","TRX":" TRON","UBQ":"Ubiq","UNIT":"UniversalCurrency","USDT":"Tether USD (Omni Layer)","VTC":"Vertcoin","WAVES":"Waves","XCP":"Counterparty","XEM":"NEM","XMR":"Monero","XSN":"Stakenet","XSR":"SucreCoin","XVG":"VERGE","XZC":"ZCoin","ZEC":"ZCash","ZEN":"Horizen"}}',
                'currency' => 'BTC',
                'deleted_at' => NULL,
                'extra_parameters' => '{"callback":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 22,
                'image' => '/files/payment_gateways/1705076328Coinpayments.png',
                'max_amount' => '99999.00000000',
                'min_amount' => '10.00000000',
                'name' => 'CoinPayments',
                'note' => '',
                'parameters' => '{"merchant_id":"86ebca4746ea46796e58538f0e6e34f6","private_key":"e177C49cc9bBb93b94A83f74229Acf6507E77d955Ba8ac0E742C71d3EC70fc6b","public_key":"c8d66aa5e9eeeaffb6c0e9cfa00108d9743bed570523d43e7fe8237841dd1be6"}',
                'percentage_charge' => '1.0000',
                'sort_by' => 6,
                'status' => 1,
                'symbol' => 'BTC',
                'updated_at' => '2024-01-12 21:18:48',
            ),
            22 =>
            array (
                'code' => 'blockchain',
                'convention_rate' => '0.00000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"1":{"BTC":"BTC"}}',
                'currency' => 'BTC',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 23,
                'image' => '/files/payment_gateways/1705076290blockchain.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '100.00000000',
                'name' => 'Blockchain',
                'note' => '',
                'parameters' => '{"api_key":"a82a8a6a-6411-452f-9741-d4ec46e541e6","xpub_code":"xpub6Cq2NpFqoqX5DRsyhebKRH2fCsBUneBpBHXyz5mZAZojesJguZJnBpG6MFGdkio1oTd3GrXoCi9HDFTC5xZoSZN7KZUpn24bPdh5dqyrkYK"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 4,
                'status' => 1,
                'symbol' => 'BTC',
                'updated_at' => '2024-01-12 21:18:10',
            ),
            23 =>
            array (
                'code' => 'midtrans',
                'convention_rate' => '1.00000000',
                'created_at' => '2023-02-08 11:17:49',
                'currencies' => '{"0":{"IDR":"IDR"}}',
                'currency' => 'IDR',
                'deleted_at' => NULL,
                'extra_parameters' => '{"payment_notification_url":"ipn", "finish redirect_url":"ipn", "unfinish redirect_url":"failed","error redirect_url":"failed"}',
                'fixed_charge' => '0.00000000',
                'id' => 24,
                'image' => '/files/payment_gateways/1705076270midtrans.png',
                'max_amount' => '1000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Midtrans',
                'note' => '',
                'parameters' => '{"client_key":"SB-Mid-client-AFE_YYsX_ig7ZCOB","server_key":"SB-Mid-server-GW1xPWLFT63nzzbecPLQzW0B"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'IDR',
                'updated_at' => '2024-05-02 16:47:44',
            ),
            24 =>
            array (
                'code' => 'cashmaal',
                'convention_rate' => '0.85000000',
                'created_at' => '2020-09-10 14:05:02',
                'currencies' => '{"0":{"PKR":"PKR","USD":"USD"}}',
                'currency' => 'PKR',
                'deleted_at' => NULL,
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 25,
                'image' => '/files/payment_gateways/1705076301cashmaal.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '2.00000000',
                'name' => 'cashmaal',
                'note' => '',
                'parameters' => '{"web_id":"9596","ipn_key":"dzgPkLJCBcYW4Q3be2yOl5ot5ApGnqXIxdw"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 5,
                'status' => 1,
                'symbol' => 'PKR',
                'updated_at' => '2024-01-12 21:18:21',
            ),
            25 =>
            array (
                'code' => 'peachpayments',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 08:05:02',
                'currencies' => '{"0":{"AED":"AED","AFA":"AFA","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZM":"AZM","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYR":"BYR","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUP":"CUP","CVE":"CVE","CYP":"CYP","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EEK":"EEK","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHC":"GHC","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LTL":"LTL","LVL":"LVL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MTL":"MTL","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZM":"MZM","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PTS":"PTS","PYG":"PYG","QAR":"QAR","RON":"RON","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDD":"SDD","SEK":"SEK","SGD":"SGD","SHP":"SHP","SIT":"SIT","SKK":"SKK","SLL":"SLL","SOS":"SOS","SPL":"SPL","SRD":"SRD","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMM":"TMM","TND":"TND","TOP":"TOP","TRL":"TRL","TRY":"TRY","TTD":"TTD","TVD":"TVD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMK":"ZMK","ZWD":"ZWD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 26,
                'image' => '/files/payment_gateways/1705076199peachpayments.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '100.00000000',
                'name' => 'peachpayments',
                'note' => '',
                'parameters' => '{"Authorization_Bearer":"**************","Entity_ID":"**************","Recur_Channel":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 11,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:16:39',
            ),
            26 =>
            array (
                'code' => 'nowpayments',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"1":{"BTC":"BTC","LTC":"LTC","DOGE":"DOGE"}}',
                'currency' => 'BTC',
                'deleted_at' => NULL,
                'extra_parameters' => '{"cron":"ipn"}',
                'fixed_charge' => '0.50000000',
                'id' => 27,
                'image' => '/files/payment_gateways/1705076153now-payments.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '10.10000000',
                'name' => 'Nowpayments',
                'note' => '',
                'parameters' => '{"api_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 7,
                'status' => 1,
                'symbol' => 'BTC',
                'updated_at' => '2024-01-12 21:15:53',
            ),
            27 =>
            array (
                'code' => 'khalti',
                'convention_rate' => '132.04000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'currency' => 'NPR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 28,
                'image' => '/files/payment_gateways/1705076234Khaltipayment.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '100.00000000',
                'name' => 'Khalti Payment',
                'note' => '',
                'parameters' => '{"secret_key":"***************","public_key":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 9,
                'status' => 1,
                'symbol' => 'NPR',
                'updated_at' => '2024-01-12 21:17:14',
            ),
            28 =>
            array (
                'code' => 'swagger',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"0":{"EUR":"EUR"}}',
                'currency' => 'EUR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 29,
                'image' => '/files/payment_gateways/1705076258maguapay.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '100.00000000',
                'name' => 'MAGUA PAY',
                'note' => '',
                'parameters' => '{"MAGUA_PAY_ACCOUNT":"***************","MerchantKey":"***************","Secret":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 8,
                'status' => 1,
                'symbol' => 'EUR',
                'updated_at' => '2024-01-12 21:17:38',
            ),
            29 =>
            array (
                'code' => 'freekassa',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"0":{"RUB":"RUB","USD":"USD","EUR":"EUR","UAH":"UAH","KZT":"KZT"}}',
                'currency' => 'RUB',
                'deleted_at' => NULL,
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'fixed_charge' => '0.00000000',
                'id' => 30,
                'image' => '/files/payment_gateways/1705076210free-kassa.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '10.00000000',
                'name' => 'Free kassa',
                'note' => '',
                'parameters' => '{"merchant_id":"***************","merchant_key":"***************","secret_word":"***************","secret_word2":"***************"}',
                'percentage_charge' => '0.1000',
                'sort_by' => 5,
                'status' => 1,
                'symbol' => 'RUB',
                'updated_at' => '2024-01-12 21:16:50',
            ),
            30 =>
            array (
                'code' => 'konnect',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"0":{"TND":"TND","EUR":"EUR","USD":"USD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => '{"webhook":"ipn"}',
                'fixed_charge' => '0.00000000',
                'id' => 31,
                'image' => '/files/payment_gateways/1705076249konnect.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Konnect',
                'note' => '',
                'parameters' => '{"api_key":"**************","receiver_wallet_Id":"**************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 4,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-12 21:17:29',
            ),
            31 =>
            array (
                'code' => 'mypay',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 02:05:02',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'currency' => 'NPR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 32,
                'image' => '/files/payment_gateways/1705076139maguapay.png',
                'max_amount' => '100000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Mypay Np',
                'note' => '',
                'parameters' => '{"merchant_username":"***************","merchant_api_password":"***************","merchant_id":"***************","api_key":"***************"}',
                'percentage_charge' => '1.5000',
                'sort_by' => 10,
                'status' => 1,
                'symbol' => 'NPR',
                'updated_at' => '2024-01-12 21:15:39',
            ),
            32 =>
            array (
                'code' => 'paythrow',
                'convention_rate' => '1.00000000',
                'created_at' => '2023-02-08 11:17:24',
                'currencies' => '{"0":{"PKR":"PKR","USD":"USD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'fixed_charge' => '0.00000000',
                'id' => 33,
                'image' => '/files/payment_gateways/1715326719paythru-logo-600x600-1.png',
                'max_amount' => '1000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'PayThrow',
                'note' => '',
                'parameters' => '{"client_id":"sadas","client_secret":"asdasd"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-05-10 12:38:39',
            ),
            33 =>
            array (
                'code' => 'imepay',
                'convention_rate' => '1.00000000',
                'created_at' => '2023-02-08 11:17:49',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'currency' => 'NPR',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 34,
                'image' => '/files/payment_gateways/1705076221imepay.png',
                'max_amount' => '1000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'IME PAY',
                'note' => '',
                'parameters' => '{"MerchantModule":"***************","MerchantCode":"***************","username":"***************","password":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'NPR',
                'updated_at' => '2024-01-12 21:17:01',
            ),
            34 =>
            array (
                'code' => 'binance',
                'convention_rate' => '1.00000000',
                'created_at' => '2023-02-08 11:17:49',
                'currencies' => '{"1":{"ADA":"ADA","ATOM":"ATOM","AVA":"AVA","BCH":"BCH","BNB":"BNB","BTC":"BTC","BUSD":"BUSD","CTSI":"CTSI","DASH":"DASH","DOGE":"DOGE","DOT":"DOT","EGLD":"EGLD","EOS":"EOS","ETC":"ETC","ETH":"ETH","FIL":"FIL","FRONT":"FRONT","FTM":"FTM","GRS":"GRS","HBAR":"HBAR","IOTX":"IOTX","LINK":"LINK","LTC":"LTC","MANA":"MANA","MATIC":"MATIC","NEO":"NEO","OM":"OM","ONE":"ONE","PAX":"PAX","QTUM":"QTUM","STRAX":"STRAX","SXP":"SXP","TRX":"TRX","TUSD":"TUSD","UNI":"UNI","USDC":"USDC","USDT":"USDT","WRX":"WRX","XLM":"XLM","XMR":"XMR","XRP":"XRP","XTZ":"XTZ","XVS":"XVS","ZEC":"ZEC","ZIL":"ZIL"}}',
                'currency' => 'USDT',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 35,
                'image' => '/files/payment_gateways/1715237856binance.png',
                'max_amount' => '1000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Binance',
                'note' => '',
                'parameters' => '{"mercent_api_key":"***************","mercent_secret":"***************"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'USDT',
                'updated_at' => '2024-05-09 11:57:36',
            ),
            35 =>
            array (
                'code' => 'cashonexHosted',
                'convention_rate' => '1.00000000',
                'created_at' => '2023-02-08 11:17:49',
                'currencies' => '{"0":{"USD":"USD"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.00000000',
                'id' => 36,
                'image' => '/files/payment_gateways/1715326689645097cab63701683003338.jpg',
                'max_amount' => '1000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Cashonex ',
                'note' => '',
                'parameters' => '{"idempotency_key":"aasdas","salt":"asdasd"}',
                'percentage_charge' => '0.0000',
                'sort_by' => 1,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-05-10 12:38:09',
            ),
            36 =>
            array (
                'code' => 'bank-transfer',
                'convention_rate' => '1.00000000',
                'created_at' => '2020-09-10 19:05:02',
                'currencies' => '{"0":{"NGN":"NGN","USD":"USD","EUR":"EUR","GBP":"GBP","ZAR":"ZAR","JPY":"JPY","INR":"INR","AUD":"AUD","CAD":"CAD","NZD":"NZD","NOK":"NOK","PLN":"PLN"}}',
                'currency' => 'USD',
                'deleted_at' => NULL,
                'extra_parameters' => NULL,
                'fixed_charge' => '0.50000000',
                'id' => 37,
                'image' => '/files/payment_gateways/1715846548bank-transfer.png',
                'max_amount' => '10000.00000000',
                'min_amount' => '1.00000000',
                'name' => 'Bank Transfer',
                'note' => '',
                'parameters' => '{}',
                'percentage_charge' => '0.0000',
                'sort_by' => 22,
                'status' => 1,
                'symbol' => 'USD',
                'updated_at' => '2024-01-13 02:11:08',
            ),
        ));


    }
}
