<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GeneralSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('general_settings')->delete();
        
        \DB::table('general_settings')->insert(array (
            0 => 
            array (
                'id' => 4,
                'name' => 'web_facebook_link',
                'display_name' => 'Facebook',
                'value' => 'https://facebook.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 19:02:32',
                'updated_at' => '2023-01-18 13:38:43',
            ),
            1 => 
            array (
                'id' => 5,
                'name' => 'web_twitter_link',
                'display_name' => 'Twitter',
                'value' => NULL,
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 18:28:25',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            2 => 
            array (
                'id' => 6,
                'name' => 'logo',
                'display_name' => 'Logo',
                'value' => '/images/settings/logo.png',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'image',
                'page' => NULL,
                'created_at' => '2023-10-12 22:01:23',
                'updated_at' => '2023-10-12 22:01:23',
            ),
            3 => 
            array (
                'id' => 11,
                'name' => 'home_section1_heading',
                'display_name' => 'Section 1 Heading',
                'value' => 'Members',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            4 => 
            array (
                'id' => 12,
                'name' => 'home_section1_icon',
                'display_name' => 'Section 1 Icon',
                'value' => 'bi bi-person-vcard-fill',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            5 => 
            array (
                'id' => 13,
                'name' => 'home_section1_value',
                'display_name' => 'Section 1 Value',
                'value' => '100',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            6 => 
            array (
                'id' => 17,
                'name' => 'home_section2_heading',
                'display_name' => 'Section 2 Heading',
                'value' => 'Lawyers',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            7 => 
            array (
                'id' => 18,
                'name' => 'home_section2_icon',
                'display_name' => 'Section 2 Icon',
                'value' => 'bi bi-person-heart',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            8 => 
            array (
                'id' => 19,
                'name' => 'home_section2_value',
                'display_name' => 'Section 2 Value',
                'value' => '77',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            9 => 
            array (
                'id' => 24,
                'name' => 'home_section3_heading',
                'display_name' => 'Section 3 Heading',
                'value' => 'Appointments Booked',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-08-25 21:36:16',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            10 => 
            array (
                'id' => 25,
                'name' => 'home_section3_icon',
                'display_name' => 'Section 3 Icon',
                'value' => 'bi bi-calendar-heart-fill',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            11 => 
            array (
                'id' => 26,
                'name' => 'home_section3_value',
                'display_name' => 'Section 3 Value',
                'value' => '97',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            12 => 
            array (
                'id' => 27,
                'name' => 'home_section4_heading',
                'display_name' => 'Section 4 Heading',
                'value' => 'LawFirms',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            13 => 
            array (
                'id' => 28,
                'name' => 'home_section4_icon',
                'display_name' => 'Section 4 Icon',
                'value' => 'bi bi-buildings-fill',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            14 => 
            array (
                'id' => 29,
                'name' => 'home_section4_value',
                'display_name' => 'Section 4 Value',
                'value' => '84',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            15 => 
            array (
                'id' => 30,
                'name' => 'web_youtube_link',
                'display_name' => 'Youtube',
                'value' => 'https://youtube.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 19:02:19',
                'updated_at' => '2023-01-18 13:38:43',
            ),
            16 => 
            array (
                'id' => 31,
                'name' => 'web_linkedin_link',
                'display_name' => 'Linkedin',
                'value' => 'https://linkedin.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 18:28:25',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            17 => 
            array (
                'id' => 32,
                'name' => 'web_whatsapp_link',
                'display_name' => 'Whatsapp',
                'value' => 'https://whatsapp.com/asd',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 18:28:25',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            18 => 
            array (
                'id' => 33,
                'name' => 'footer_crisis_support_statement',
                'display_name' => 'Footer Crisis Support Statement',
                'value' => '<b>Don\'t use this site if:</b> You are in a crisis or if any other person may be in danger.',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'textarea',
                'page' => 'website_footer',
                'created_at' => '2023-01-18 23:17:32',
                'updated_at' => '2023-01-18 18:16:43',
            ),
            19 => 
            array (
                'id' => 34,
                'name' => 'web_instagram_link',
                'display_name' => 'Instagram',
                'value' => 'https://instagram.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 19:06:10',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            20 => 
            array (
                'id' => 35,
                'name' => 'web_snapchat_link',
                'display_name' => 'Snapchat',
                'value' => 'https://snapchat.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 19:02:19',
                'updated_at' => '2023-01-18 13:38:43',
            ),
            21 => 
            array (
                'id' => 36,
                'name' => 'web_pinterest_link',
                'display_name' => 'Pinterest',
                'value' => 'https://pinterest.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 18:28:25',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            22 => 
            array (
                'id' => 37,
                'name' => 'web_tiktok_link',
                'display_name' => 'TikTok',
                'value' => 'https://tiktok.com',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2023-01-21 18:28:25',
                'updated_at' => '2023-01-21 17:28:25',
            ),
            23 => 
            array (
                'id' => 38,
                'name' => 'home_section5_heading',
                'display_name' => 'Section 5 Heading',
                'value' => 'Events',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            24 => 
            array (
                'id' => 39,
                'name' => 'home_section5_icon',
                'display_name' => 'Section 5 Icon',
                'value' => 'bi bi-balloon-heart-fill',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            25 => 
            array (
                'id' => 40,
                'name' => 'home_section5_value',
                'display_name' => 'Section 5 Value',
                'value' => '100',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            26 => 
            array (
                'id' => 41,
                'name' => 'agora_app_id',
                'display_name' => 'AGORA APP ID',
                'value' => 'ee3d69d271fb409e93347069503f4803',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            27 => 
            array (
                'id' => 43,
                'name' => 'agora_app_certificate',
                'display_name' => 'AGORA APP CERTIFICATE',
                'value' => '3f8f4c99dc2748db88a286fbbfc6b1c7',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            28 => 
            array (
                'id' => 44,
                'name' => 'pusher_beams_instance_id',
                'display_name' => 'PUSHER BEAMS INSTANCE ID',
                'value' => 'aa80356b-825a-4493-b7a0-5257859f6fc2',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            29 => 
            array (
                'id' => 45,
                'name' => 'pusher_beams_secret_key',
                'display_name' => 'PUSHER BEAMS SECRET KEY',
                'value' => '189B85C37FAF9E0759CD695A535202D0BD1B5D97A62DD487CAF0C0B9B0877AAA',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            30 => 
            array (
                'id' => 46,
                'name' => 'pusher_app_id',
                'display_name' => 'PUSHER APP ID',
                'value' => '1926621',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            31 => 
            array (
                'id' => 47,
                'name' => 'pusher_app_key',
                'display_name' => 'PUSHER APP KEY',
                'value' => '66ee623b8b65063f08ad',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            32 => 
            array (
                'id' => 48,
                'name' => 'pusher_app_secret',
                'display_name' => 'PUSHER APP SECRET',
                'value' => 'd0708b283e2ed6a9e946',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            33 => 
            array (
                'id' => 49,
                'name' => 'pusher_app_cluster',
                'display_name' => 'PUSHER APP CLUSTER',
                'value' => 'ap2',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            34 => 
            array (
                'id' => 50,
                'name' => 'stripe_key',
                'display_name' => 'STRIPE KEY',
                'value' => 'pk_test_51MjnELHTAHWwyrB6HqKFzapBSOjSEAF9dKUz7JAI9vPTQHtsGsFJrhm151hdiVQWyvsvtq1CpkSMEmAUjC0pgbEl00P1BNfXvD',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'payment_method_settings',
                'created_at' => '2024-12-31 15:59:46',
                'updated_at' => '2023-11-01 17:18:22',
            ),
            35 => 
            array (
                'id' => 51,
                'name' => 'stripe_secret',
                'display_name' => 'STRIPE SECRET',
                'value' => 'sk_test_51MjnELHTAHWwyrB6o5FbJewlU1QQeOvwfJoCBfnlf20KzNGa7JVyxIWhYIb84Ohl8kUxvGDuzOkCSo3rFj9Ne85l00FvdXN2ti',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'payment_method_settings',
                'created_at' => '2024-12-31 15:59:46',
                'updated_at' => '2023-11-01 17:18:22',
            ),
            36 => 
            array (
                'id' => 52,
                'name' => 'google_client_id',
                'display_name' => 'GOOGLE CLIENT ID',
                'value' => '1006558285844-81r1j9n23vovqg9uebrae8tcg79v7t4b.apps.googleusercontent.com',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            37 => 
            array (
                'id' => 53,
                'name' => 'google_client_secret',
                'display_name' => 'GOOGLE CLIENT SECRET',
                'value' => 'Uru8dkoJjf3ey401DG8gLaq5',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            38 => 
            array (
                'id' => 54,
                'name' => 'facebook_client_id',
                'display_name' => 'FACEBOOK CLIENT ID',
                'value' => '887082349379468',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            39 => 
            array (
                'id' => 55,
                'name' => 'facebook_client_secret',
                'display_name' => 'FACEBOOK CLIENT SECRET',
                'value' => '163a1cc69bd8a9706700e816544b1429',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2025-01-16 13:17:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            40 => 
            array (
                'id' => 56,
                'name' => 'contact_us_email',
                'display_name' => 'Contact Us Receiving Email',
                'value' => 'info@hexathemes.com',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'email',
                'page' => NULL,
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            41 => 
            array (
                'id' => 57,
                'name' => 'site_title',
                'display_name' => 'Site Title',
                'value' => 'Law Advisor',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => NULL,
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            42 => 
            array (
                'id' => 59,
                'name' => 'enable_wallet_system',
                'display_name' => 'Enable Wallet System',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => NULL,
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            43 => 
            array (
                'id' => 60,
                'name' => 'commission_type',
                'display_name' => 'Select Commission Type',
                'value' => 'commission_base',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'select_option',
                'page' => NULL,
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            44 => 
            array (
                'id' => 61,
                'name' => 'application_current_version',
                'display_name' => 'Application Current Version',
                'value' => '2.0.2',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => NULL,
                'created_at' => '2025-01-16 17:07:07',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            45 => 
            array (
                'id' => 62,
                'name' => 'mail_driver',
                'display_name' => 'Mail Driver',
                'value' => 'smtp',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            46 => 
            array (
                'id' => 63,
                'name' => 'mail_host',
                'display_name' => 'Mail Host',
                'value' => 'sandbox.smtp.mailtrap.io',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            47 => 
            array (
                'id' => 64,
                'name' => 'mail_port',
                'display_name' => 'Mail Port',
                'value' => '587',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            48 => 
            array (
                'id' => 65,
                'name' => 'mail_username',
                'display_name' => 'Mail Username',
                'value' => '5e61912602edf9',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            49 => 
            array (
                'id' => 66,
                'name' => 'mail_password',
                'display_name' => 'Mail Password',
                'value' => '275f0deee12cf5',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            50 => 
            array (
                'id' => 67,
                'name' => 'mail_encryption',
                'display_name' => 'Mail Encryption',
                'value' => 'null',
                'is_protected' => 1,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'email_settings',
                'created_at' => '2025-02-18 14:27:44',
                'updated_at' => '2025-01-16 13:17:44',
            ),
            51 => 
            array (
                'id' => 68,
                'name' => 'auto_approve_lawyer_service',
                'display_name' => 'Auto Approve Lawyer Service',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            52 => 
            array (
                'id' => 69,
                'name' => 'auto_approve_law_firm_service',
                'display_name' => 'Auto Approve Law Firm Service',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            53 => 
            array (
                'id' => 76,
                'name' => 'is_community_form_show',
                'display_name' => 'Show Community Form',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            54 => 
            array (
                'id' => 77,
                'name' => 'is_ai_chatbot_enable',
                'display_name' => 'Is AI chatBot Enable',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            55 => 
            array (
                'id' => 78,
                'name' => 'is_auto_approve',
                'display_name' => 'Auto Approve Users',
                'value' => '1',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => NULL,
                'created_at' => '2025-01-14 16:03:33',
                'updated_at' => '2025-01-14 16:03:33',
            ),
            56 => 
            array (
                'id' => 79,
                'name' => 'favicon',
                'display_name' => 'FavIcon',
                'value' => '/images/settings/favicon.png',
                'is_protected' => 0,
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'image',
                'page' => NULL,
                'created_at' => '2025-01-02 21:47:50',
                'updated_at' => '2025-01-02 16:47:50',
            ),
            57 => 
            array (
                'id' => 80,
                'name' => 'seo_title',
                'display_name' => 'SEO title',
                'value' => 'Law Advisor',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'seo_settings',
                'created_at' => '2025-02-18 14:28:42',
                'updated_at' => '2025-01-29 12:18:48',
            ),
            58 => 
            array (
                'id' => 81,
                'name' => 'meta_description',
                'display_name' => 'Meta Description',
                'value' => '<p>Stay informed and inspired with our Hexathemes, delivering the latest news, trends, and insights in lifestyle, technology, health, and more. Explore exclusive articles, in-depth analysis, and expert opinions tailored for curious minds and savvy readers.</p>',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'textarea',
                'page' => 'seo_settings',
                'created_at' => '2025-01-29 17:18:48',
                'updated_at' => '2025-01-29 12:18:48',
            ),
            59 => 
            array (
                'id' => 82,
                'name' => 'meta_keywords',
                'display_name' => 'Meta Keywords',
                'value' => '["websites","law-advisor","lawyers","lawfirm"]',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'array',
                'page' => 'seo_settings',
                'created_at' => '2025-01-29 17:18:48',
                'updated_at' => '2025-01-29 12:18:48',
            ),
            60 => 
            array (
                'id' => 83,
                'name' => 'social_description',
                'display_name' => 'Social Description',
                'value' => '<p>Stay informed and inspired with our Hexathemes, delivering the latest news, trends, and insights in lifestyle, technology, health, and more. Explore exclusive articles, in-depth analysis, and expert opinions tailored for curious minds and savvy readers.</p>',
                'is_protected' => 0,
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'textarea',
                'page' => 'seo_settings',
                'created_at' => '2025-01-29 17:18:48',
                'updated_at' => '2025-01-29 12:18:48',
            ),
        ));
        
        
    }
}