<?php

return [
    'Attorney' => [
        'General attorney',
        'Tax attorney',
        'Real estate attorney',
        'Family law attorney',
        'Criminal defense attorney',
        'Immigration attorney',
        'Corporate attorney',
        'Employment attorney',
        'Personal injury attorney',
        'Bankruptcy attorney',
        'Estate planning attorney',
        'Intellectual property attorney',
        'Civil rights attorney',
        'DUI attorney',
        'Medical malpractice attorney',
        'Workers compensation attorney',
        'Environmental attorney',
        'Elder law attorney',
        'Litigation attorney',
        'Patent attorney',
        'Trademark attorney',
    ],
    'Lawyer' => [
        'Personal injury lawyer',
        'Corporate lawyer',
        'Employment lawyer',
        'Divorce lawyer',
        'Bankruptcy lawyer',
        'Civil rights lawyer',
        'Criminal defense lawyer',
        'Family law lawyer',
        'Real estate lawyer',
        'Estate planning lawyer',
        'Immigration lawyer',
        'Intellectual property lawyer',
        'Tax lawyer',
        'Patent lawyer',
        'Trademark lawyer',
        'Litigation lawyer',
        'Environmental lawyer',
        'Medical malpractice lawyer',
        'DUI lawyer',
        'Elder law lawyer',
    ],
    'Murder' =>[
        'Murder',
        'Murder investigation',
        'Murder defense',
        'Murder conviction',
        'Murder trial',
        'Murder prevention',
        'Murder prevention education',
        'Murder prevention awareness',
        'Murder prevention resources',
        'Murder prevention support',
        'Murder prevention tips',
        'Murder prevention strategies',
        'Murder prevention education materials',
        'Murder prevention education programs',
        'Murder prevention education resources',
        'Murder prevention education centers',
        'Murder prevention education seminars',
        'Murder prevention education workshops',
        'Murder prevention education forums',
        'Murder prevention education forums online',
        'Murder prevention education forums offline',
    ],
    'Legal Advice' => [
        'Legal consultation',
        'Legal counsel',
        'Legal representation',
        'Legal assistance',
        'Legal guidance',
        'Legal expertise',
        'Legal opinion',
        'Legal advice hotline',
        'Legal helpline',
        'Free legal advice',
        'Affordable legal advice',
    ],
    'Law Firm' => [
        'Law firm',
        'Legal firm',
        'Boutique law firm',
        'Full-service law firm',
        'Virtual law firm',
        'International law firm',
        'Local law firm',
        'Top law firm',
        'Reputable law firm',
        'Corporate law firm',
    ],
    'Legal Services' => [
        'Legal services',
        'Legal aid',
        'Pro bono legal services',
        'Legal representation',
        'Court representation',
        'Legal case management',
        'Legal research',
        'Legal drafting',
        'Legal compliance',
        'Legal strategy',
        'Document preparation services',
        'Legal documentation',
        'Legal document review',
        'Legal document automation',
        'Online legal services',
        'Virtual legal services',
        'Remote legal services',
        'Mobile notary services',
        'Contract review services',
    ],
    'Legal Process' => [
        'Litigation',
        'Arbitration',
        'Mediation',
        'Settlement negotiation',
        'Legal filing',
        'Court representation',
        'Alternative dispute resolution',
        'Pre-litigation services',
        'Trial preparation',
        'Appellate services',
        'Discovery process',
        'Pleading preparation',
        'Deposition services',
        'Expert witness services',
    ],
    'Legal Documents' => [
        'Will and testament',
        'Power of attorney',
        'Legal contracts',
        'Legal agreements',
        'Non-disclosure agreement',
        'Partnership agreement',
        'Lease agreement',
        'Employment contract',
        'Service agreement',
        'Terms of service',
        'Privacy policy',
        'Corporate bylaws',
        'Operating agreement',
        'Trust documents',
        'Estate planning documents',
    ],
    'Specialized Legal Services' => [
        'Small business legal services',
        'Corporate legal services',
        'Nonprofit legal services',
        'Start-up legal services',
        'High-net-worth individuals',
        'Intellectual property services',
        'Patent filing services',
        'Trademark registration',
        'Immigration services',
        'Elder law services',
        'Estate administration',
        'Guardianship services',
        'Environmental law services',
        'Healthcare law services',
        'Employment law services',
        'Family law services',
        'Entertainment law services',
    ],
    'Legal Technology' => [
        'Legal tech solutions',
        'Legal software',
        'E-discovery',
        'Legal research tools',
        'Document management system',
        'Case management software',
        'Contract management software',
        'Legal billing software',
        'Time tracking software for lawyers',
        'Virtual law office',
        'AI legal assistant',
        'Online legal platforms',
        'Legal chatbots',
    ],
    'Other Legal Keywords' => [
        'Law office',
        'Local legal help',
        'Legal billing',
        'Legal compliance',
        'Legal research',
        'Legal drafting',
        'Legal strategy',
        'Online legal consultation',
        'Remote legal advice',
        'Virtual legal services',
        'Legal tech solutions',
        'Legal document automation',
        'Corporate lawyer',
        'Civil litigation',
        'White-collar crime',
        'Public defender',
        'Defense attorney',
        'Prosecutor',
        'Barrister',
        'Solicitor',
        'Paralegal',
        'Notary public',
        'Legal secretary',
        'Legal assistant',
        'Court reporter',
        'Court clerk',
        'Jury consultant',
        'Trial consultant',
    ],
    'Legal Industry' => [
        'Legal market',
        'Legal trademark',
        'Legal patent',
    ],
    'Divorce',
    'Family Law',
    'Criminal Defense',
    'Immigration',
    'Corporate Law',
    'Employment',
    'Personal Injury',
    'Bankruptcy',
    'Estate Planning',
    'Intellectual Property',
    'Civil Rights',
    'DUI',
    'Medical Malpractice',
    'Workers Compensation',
    'Environmental',
    'Elder Law',
    'Litigation',
    'Patent',
    'Trademark',
    'Environmental Law',
    'Healthcare Law',
    'Employment Law',
    'Family Law',
    'Entertainment Law',
    'Small Business',
    'Corporate',
    'Nonprofit',
    'Start-up',
    'High-net-worth',
    'Intellectual Property',
    'Immigration',
    'Estate Administration',
];
